### ISSUE TITLE
SystemError: initialization of _heapq did not return an extension module

### ISSUE THREAD

**Issue by OliverEvans96** [JuliaPy/pyjulia#150]
I'm experiencing the same error mentioned by @sirgogo in #88 .

```python
oliver@oliver-arch:~ % ipython
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 23:12:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import julia

In [2]: j = julia.Julia()
Error processing line 1 of /home/oliver/local/miniconda3/lib/python3.5/site-packages/PyUtilib-5.4.1-py2.7-nspkg.pth:

Failed to import the site module
Traceback (most recent call last):
  File "/home/oliver/local/miniconda3/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/oliver/local/miniconda3/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/home/oliver/local/miniconda3/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/home/oliver/local/miniconda3/lib/python3.5/collections/__init__.py", line 29, in <module>
    import heapq as _heapq
  File "/home/oliver/local/miniconda3/lib/python3.5/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oliver/local/miniconda3/lib/python3.5/site.py", line 559, in <module>
    main()
  File "/home/oliver/local/miniconda3/lib/python3.5/site.py", line 541, in main
    known_paths = addsitepackages(known_paths)
  File "/home/oliver/local/miniconda3/lib/python3.5/site.py", line 318, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/oliver/local/miniconda3/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/oliver/local/miniconda3/lib/python3.5/site.py", line 177, in addpackage
    import traceback
  File "/home/oliver/local/miniconda3/lib/python3.5/traceback.py", line 3, in <module>
    import collections
  File "/home/oliver/local/miniconda3/lib/python3.5/collections/__init__.py", line 29, in <module>
    import heapq as _heapq
  File "/home/oliver/local/miniconda3/lib/python3.5/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module
```

I'm running Arch Linux and using the following versions:

| Package| Version |
|---|---|
| python | 3.5.5 :: Anaconda, Inc. |
| julia | 0.6.2 |
| PyJulia | 0.1.5 |
| PyCall | 1.15.0 |

Any advice is appreciated!

Thanks,
Oliver

**Comment by SHTILL** [comment]
Have exactly the same error:
Error processing line 1 of /home/vasya/anaconda3/lib/python3.6/site-packages/matplotlib-2.1.2-py3.6-nspkg.pth:

**Comment by matteoacrossi** [comment]
I have a similar error but it happens in `matplotlib`

<details>
<summary>

`SystemError: initialization of _heapq did not return an extension module`

</summary>

```
Python 3.5.5 |Anaconda custom (64-bit)| (default, Mar 12 2018, 16:25:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import julia
>>> j = julia.Julia()
Error processing line 1 of /Users/matteo/anaconda/lib/python3.5/site-packages/matplotlib-2.2.2-py3.5-nspkg.pth:

Failed to import the site module
Traceback (most recent call last):
  File "/Users/matteo/anaconda/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/matteo/anaconda/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/Users/matteo/anaconda/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/matteo/anaconda/lib/python3.5/collections/__init__.py", line 29, in <module>
    import heapq as _heapq
  File "/Users/matteo/anaconda/lib/python3.5/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matteo/anaconda/lib/python3.5/site.py", line 559, in <module>
    main()
  File "/Users/matteo/anaconda/lib/python3.5/site.py", line 541, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/matteo/anaconda/lib/python3.5/site.py", line 318, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/matteo/anaconda/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/matteo/anaconda/lib/python3.5/site.py", line 177, in addpackage
    import traceback
  File "/Users/matteo/anaconda/lib/python3.5/traceback.py", line 3, in <module>
    import collections
  File "/Users/matteo/anaconda/lib/python3.5/collections/__init__.py", line 29, in <module>
    import heapq as _heapq
  File "/Users/matteo/anaconda/lib/python3.5/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module
```

</details>

**Comment by carmagnole** [comment]
I have the same problem:

julia.Julia(debug = True)
JULIA_HOME = /Applications/Julia-0.6.app/Contents/Resources/julia/bin,  libjulia_path = /Applications/Julia-0.6.app/Contents/Resources/julia/lib/libjulia.0.6.2.dylib
calling jl_init_with_image(b'/Applications/Julia-0.6.app/Contents/Resources/julia/bin', /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib)
seems to work...
exception occured? None
Failed to import the site module
Traceback (most recent call last):
  File "/anaconda3/envs/Neuroscience/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/anaconda3/envs/Neuroscience/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/anaconda3/envs/Neuroscience/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/anaconda3/envs/Neuroscience/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/anaconda3/envs/Neuroscience/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/anaconda3/envs/Neuroscience/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/anaconda3/envs/Neuroscience/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/anaconda3/envs/Neuroscience/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
  File "/anaconda3/envs/Neuroscience/lib/python3.6/re.py", line 122, in <module>
    import enum
  File "/anaconda3/envs/Neuroscience/lib/python3.6/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/anaconda3/envs/Neuroscience/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/anaconda3/envs/Neuroscience/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/anaconda3/envs/Neuroscience/lib/python3.6/collections/__init__.py", line 29, in <module>
    import heapq as _heapq
  File "/anaconda3/envs/Neuroscience/lib/python3.6/heapq.py", line 587, in <module>
    from _heapq import *
SystemError: initialization of _heapq did not return an extension module

**Comment by tkf** [comment]
Hmm... I thought I fixed #175 by [this commit](https://github.com/JuliaPy/pyjulia/pull/190/commits/d49d819d7a5343998e7314010635ede278b2190f). Does it happen with PyJulia master as well?

I remember it happened with Julia 0.6 when the precompilation failed.

**Comment by bstellato** [comment]
Yes I am using the master and Julia 1.0. I deleted the `~/.julia/compiled/v1.0/PyCall/xxx.ji` file before but it does not seem to help. The `ctypes` code here in https://github.com/JuliaPy/pyjulia/issues/150#issuecomment-392282859 gives the same answer for me.

**Comment by tkf** [comment]
Julia 1.0 with miniconda is not supported ATM so it is supposed to print some informative error message.  Are you using Linux?

If you use miniconda in Linux, `python-jl` is probably the best way to make it work: https://github.com/tkf/pyjulia/blob/readme/README.md#your-python-interpreter-is-statically-linked-to-libpython

**Comment by bstellato** [comment]
I am using Mac but it actually works with `python-jl` and Julia 1.0. Thanks a lot! However, it would be great to have the anaconda python working without that hack.

**Comment by tkf** [comment]
Good that it works!

BTW, in your comment you are mentioning you tried `ldd`, right?  Meaning that

```
ldd PATH/TO/YOUR/python
```

doesn't show libpython?  Do you actually have `ldd` in macOS?  I thought it's different command.

Additionally, can you run the following in miniconda `python` (_not_ `python-jl`) you were using?

```python
from julia.find_libpython import find_libpython, linked_libpython
linked_libpython()  # what does it return?
find_libpython()    # what does it return?
```

I thought macOS didn't need `python-jl`.  But if `linked_libpython()` above returns `None` it means our assumption was not correct...

> it would be great to have the anaconda python working without that hack

Yeah I know... But I can't do anything now. :crying_cat_face:

**Comment by bstellato** [comment]
Sorry, I meant `otool -L`! Unfortunately it does not list anything related to libpython.

I have tried your commands. 

* `linked_libpython()` returns `None`. 
* `find_libpython()` returns the right library `/Users/xxx/miniconda3/envs/python36/lib/libpython3.6m.dylib`

Thanks for the quick responses by the way :)

**Comment by tkf** [comment]
You are welcome :)  And thanks for trying the commands.  Good to figure out that `linked_libpython()` can return `None` in macOS (I mean, it's bad, but better than not knowing it...).

**Comment by sblinz** [comment]
Remove `~/.julia/lib/v0.6/PyCall.jl` worked for me. System info below:

OS: Ubuntu 16.04
Julia: v0.6
Python: 3.5.2
Virtual Environment: Conda rllab (https://github.com/rll/rllab/blob/master/environment.yml)
